name: "Publish Unreleased Changelog"
author: "PhantasmicDev"
description: "A simple GitHub action that replaces the [Unreleased] heading with the new specified release title and date."
branding:
  icon: "tag"
  color: "green"

inputs:
  release-title:
    description: "The new release title to replace the unreleased heading with."
    required: true
  changelog-path:
    description: "The path to the changelog file."
    required: false
    default: "CHANGELOG.md"
  time-zone:
    description: "The TZ database name for the target time zone, used to extract the date."
    required: false
    default: "Etc/UTC"

runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        INPUT_RELEASE_TITLE: ${{ release-title }}
        INPUT_CHANGELOG_PATH: ${{ inputs.changelog-path }}
        INPUT_TIME_ZONE: ${{ inputs.time-zone }}
